### PR TITLE
Ugly fix for plugin2 compat

### PR DESCRIPTION
**Pull request by SysPete**
This is *not* something I'm suggesting you merge but it does work for current D2 master with zero response fix (and others) and also with latest yanick-plugins branch.

### CODE REVIEW

**Comment by ambs** [comment]
:+1: 
Thank you! Next weekend, if not before, I'll look into it and try to understand what can be done :-)

**Comment by SysPete** [comment]
Having learned more about plugin2 in the last 2 days fixing up D2::P::Auth::Extensible and friends I'll have a better fix in the next day or so. Will ping here when PR is updated.

**Comment by SysPete** [comment]
@ambs now I've finally got back to looking at this I don't really see many better ways of keeping backwards compatibility whilst working with plugin2. We could use some other method for the can check but that gains nothing.

I have update the pod coverage test so it doesn't fail on the plugin2 compat layer DSL so I guess all we need now is a new release (please). :smile:

**Comment by ambs** [comment]
Question: does it make sense to wait for the new plugin system to come out, and release a new version that works only with the new plugin system?

Not sure if this is a silly question,  i didn't look yet to your code (being really busy lately)

**Comment by SysPete** [comment]
On 19/01/16 17:49, Alberto Simões wrote:
>
> Question: does it make sense to wait for the new plugin system to come
> out, and release a new version that works only with the new plugin system?
>
> Not sure if this is a silly question, i didn't look yet to your code
> (being really busy lately)
>
>
The change to support both old and new is about 4 lines extra so
releasing a version that works with both is probably a no-brainer.

P

**Comment by ambs** [comment]
:+1:

**Comment by ambs** [comment]
Merged and released. Thanks :-)

**Comment by SysPete** [comment]
Excellent! This takes us past 70% of released plugins confirmed to be working with current release and plugin2.

**Comment by ambs** [comment]
Thanks for your effort on this fight :)

**Pull request merged**
